open-weather-map:
  base-url: https://api.openweathermap.org/data/2.5
  api-version: 2.5
  default-http-timeout-millis: 60000
  api-key: 24e3fa860c58db24391dfa00fde3ce63

spring:
  security:
    user:
      name: admin
      password: admin
